---
- name: Generate local user report
  hosts: all
  gather_facts: true

  vars:
    report_title: "Local User Report"
    report_file: "/tmp/local_user_report.html"
    report_email: "ykumarap@example.com"

  tasks:

    - name: Get local users
      ansible.builtin.getent:
        database: passwd
      register: local_users

    - name: Display local_users variable
      ansible.builtin.debug:
        var: local_users

    - name: Prepare user list for HTML
      set_fact:
        user_list: "{{ local_users.ansible_facts.getent_passwd }}"

    - name: Render HTML report
      ansible.builtin.template:
        src: "templates/user_report.html.j2"
        dest: "{{ report_file }}"
      vars:
        users: "{{ user_list }}"
        title: "{{ report_title }}"

    - name: Email report
      ansible.builtin.mail:
        port: 25
        to: "{{ report_email }}"
        subject: "{{ report_title }}"
        body: "Please find the attached report."
        attach:
          - "{{ report_file }}"
